In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
from urllib.request import Request, urlopen 
%matplotlib inline
import matplotlib.dates as mdates
from matplotlib.dates import DateFormatter
import seaborn as sns
from datetime import datetime, timedelta
import time
import calendar
from pandas_datareader import data,wb
from pandas.tseries.offsets import BQuarterBegin

In [5]:
#check data
df_Technologies = pd.read_csv("Technology Sector Index.csv")
df_Communications = pd.read_csv("Communications Services Sector Index.csv")
df_Consumer = pd.read_csv("Consumer Discretionary Sector Index.csv")
df_Health = pd.read_csv("Health Care Sector Index.csv")

df_Technologies["Sector"]='Technologies'
df_Communications["Sector"]='Communications'
df_Consumer ["Sector"]='Consumer'
df_Health ["Sector"]='Health'

#df_Communications.head()
#df_Technologies.info()
#df_Communications.info()
df_Technologies['Close'] = df_Technologies['Close'].str.replace(",", "").astype(float)
df_Health['Close'] = df_Health['Close'].str.replace(",", "").astype(float)
df_Consumer['Close'] = df_Consumer['Close'].str.replace(",", "").astype(float)

df_Index  =df_Technologies


df_Index['Date'] = pd.to_datetime(df_Index['Date'], format='%d/%m/%Y')

#df_Index['Close'] = df_Index['Close'].str.replace(",", "").astype(float)

# start_2021 = '01-01-2021'
# end_2021 = '31-12-2021'
# date_2021 = (df_Index['Date'] >= start_2021) & (df_Index['Date'] <= end_2021)
# data_daily=df_Index.loc[date_2021]
# data_daily['Daily change Close Price by company'] =data_daily.groupby(['Sector'])['Close'].pct_change()
# data_daily
# data = df_Index.loc[date_2021].set_index('Date') 
# data['quarter change Close Price by company'] = data.groupby(['Sector']).Close.pct_change(freq='Q', axis =1)
# data

start_2021 = '01/01/2021'
end_2021 = '31/12/2021'
df_Index.tail(500)

date_2021 = (df_Index['Date'] >= start_2021) & (df_Index['Date'] <= end_2021)


# #df_Index_2021=df_Index.loc[date_2021]
# #df_Consumer
# #df_Index_2021
df_Index = df_Index.loc[date_2021].set_index('Date') 
# #df_Index_2021t = df_Index_2021.set_index('Date')
print ('a')
#df_Index_2021[df_Index_2021.index.duplicated()] 
# #df_Consumer.info()
# #df_Index_2021.info()
# df_Index.info()
#df_Index.reset_index(inplace=True)
#ignore_index=True

df_Index['Q Change Price2'] = df_Index.groupby(['Sector'])['Close'].pct_change( freq='Q' )
df_Index
#data['quarter change Close Price by company'] = data.groupby('company').Close.pct_change(freq='Q')

#df_Index_2021

#df_Index_2021 = df_Index_2021.loc[date_2021].set_index('Date') 
#df_Index_2021['Q Change Price'] = df_Index_2021[ " Close"].pct_change(freq='Q')


#q1 = df_Index_2021.loc['2021-03-31':'2021-03-31']
#q2 = df_Index_2021.loc['2021-06-30':'2021-06-30']
#q3 = df_Index_2021.loc['2021-09-30':'2021-09-30']
#q4 = df_Index_2021.loc['2021-12-31':'2021-12-31']
#df_Index_2021_Yearly = pd.concat([q1, q2, q3, q4])
#df_Index_2021_Yearly

#final = df_Sector.agg({' Close':['mean']})

#final.head()
#df_Communications.tail()
#df_Communications.info()

a

C:\Users\User\anaconda3\lib\site-packages\pandas\core\arraylike.py:52: UserWarning: Parsing '31/12/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  return self._cmp_method(other, operator.le)

,Open,High,Low,Close,Sector,Q Change Price2
Date,,,,,,
2021-12-31,"3,070.42","3,055.45","3,055.45",3055.45,Technologies,-0.004876
2021-12-30,"3,091.36","3,070.42","3,070.42",3070.42,Technologies,NaN
2021-12-29,"3,089.10","3,091.36","3,091.36",3091.36,Technologies,NaN
2021-12-28,"3,107.46","3,089.10","3,089.10",3089.10,Technologies,NaN
2021-12-27,"3,041.12","3,107.46","3,107.46",3107.46,Technologies,NaN
...,...,...,...,...,...,...
2021-01-08,"2,283.97","2,301.17","2,301.17",2301.17,Technologies,NaN
2021-01-07,"2,225.02","2,283.97","2,283.97",2283.97,Technologies,NaN
2021-01-06,"2,265.93","2,225.02","2,225.02",2225.02,Technologies,NaN
2021-01-05,"2,250.17","2,265.93","2,265.93",2265.93,Technologies,NaN
2021-01-04,"2,291.28","2,250.17","2,250.17",2250.17,Technologies,NaN